"==
"Author :ljl
"Website :https://github.com/Melody12ab
"Version :1.0
"==


set guifont=Consolas\ 14

"colorscheme desert
syntax enable
syntax on

set tags=tags
set autochdir
let Tlist_Show_One_File=1 
let Tlist_Exit_OnlyWindow=1

set number
set ruler
set laststatus=1
set showcmd
set magic
set cursorline
set ignorecase
let loaded_matchparen=1
set tabstop=4
set softtabstop=4
set cindent shiftwidth=4
set expandtab
set autoindent shiftwidth=4
set smartindent shiftwidth=4
set hlsearch
set incsearch

set mouse=a
set backspace=indent,eol,start


let Tlist_Show_One_File = 1 "不同时显示多个文件的tag，只显示当前文件的
let Tlist_Exit_OnlyWindow = 1 "如果 taglist 窗口是最后一个窗口，则退出 vim
let Tlist_Use_Right_Window = 1 "在右侧窗口中显示 taglist 窗口


autocmd FileType python set omnifunc=pythoncomplete#Complete
let g:pydiction_location = '/usr/share/vim/vim74/pydiction/complete-dict'
let g:pydiction_menu_height = 6
filetype plugin on 

