# Path to your oh-my-zsh installation.
  export ZSH=/home/xiaobai/.oh-my-zsh

# Set name of the theme to load.
# Look in ~/.oh-my-zsh/themes/
# Optionally, if you set this to "random", it'll load a random theme each
# time that oh-my-zsh is loaded.
# gentoo  michelebologna
ZSH_THEME="gentoo"

# Uncomment the following line to use case-sensitive completion.
# CASE_SENSITIVE="true"

# Uncomment the following line to use hyphen-insensitive completion. Case
# sensitive completion must be off. _ and - will be interchangeable.
# HYPHEN_INSENSITIVE="true"

# Uncomment the following line to disable bi-weekly auto-update checks.
# DISABLE_AUTO_UPDATE="true"

# Uncomment the following line to change how often to auto-update (in days).
# export UPDATE_ZSH_DAYS=13

# Uncomment the following line to disable colors in ls.
# DISABLE_LS_COLORS="true"

# Uncomment the following line to disable auto-setting terminal title.
# DISABLE_AUTO_TITLE="true"

# Uncomment the following line to enable command auto-correction.
# ENABLE_CORRECTION="true"

# Uncomment the following line to display red dots whilst waiting for completion.
# COMPLETION_WAITING_DOTS="true"

# Uncomment the following line if you want to disable marking untracked files
# under VCS as dirty. This makes repository status check for large repositories
# much, much faster.
# DISABLE_UNTRACKED_FILES_DIRTY="true"

# Uncomment the following line if you want to change the command execution time
# stamp shown in the history command output.
# The optional three formats: "mm/dd/yyyy"|"dd.mm.yyyy"|"yyyy-mm-dd"
# HIST_STAMPS="mm/dd/yyyy"

# Would you like to use another custom folder than $ZSH/custom?
# ZSH_CUSTOM=/path/to/new-custom-folder

# Which plugins would you like to load? (plugins can be found in ~/.oh-my-zsh/plugins/*)
# Custom plugins may be added to ~/.oh-my-zsh/custom/plugins/
# Example format: plugins=(rails git textmate ruby lighthouse)
# Add wisely, as too many plugins slow down shell startup.
plugins=(git archlinux common-aliases fbterm mvn svn-fast-info zsh-syntax-highlighting zsh-autosuggestions wd autojump)

# User configuration

# export PATH="/usr/bin:/bin:/usr/sbin:/sbin:$PATH"
# export MANPATH="/usr/local/man:$MANPATH"

source $ZSH/oh-my-zsh.sh

# You may need to manually set your language environment
# export LANG=en_US.UTF-8

# Preferred editor for local and remote sessions
# if [[ -n $SSH_CONNECTION ]]; then
#   export EDITOR='vim'
# else
#   export EDITOR='mvim'
# fi

# Compilation flags
# export ARCHFLAGS="-arch x86_64"

# ssh
# export SSH_KEY_PATH="~/.ssh/dsa_id"

# Set personal aliases, overriding those provided by oh-my-zsh libs,
# plugins, and themes. Aliases can be placed here, though oh-my-zsh
# users are encouraged to define aliases within the ZSH_CUSTOM folder.
# For a full list of active aliases, run `alias`.
#
# Example aliases
# alias zshconfig="mate ~/.zshrc"
# alias ohmyzsh="mate ~/.oh-my-zsh"
for color in RED GREEN YELLOW BLUE MAGENTA CYAN WHITE; do
    eval _$color='%{$terminfo[blod]$fg[${(L)color}]%}'
    eval $color='%{$fg[${(L)color}]%}'
    (( count = $count + 1 ))
done
FINISH="%{$terminfo[sgr0]%}"
RPROMPT=$(echo "$RED%D %T$FINISH")
PROMPT=$(echo "$BLUE%n@$YELLOW%M:$GREEN%/$_YELLOW>$FINISH ")
PROMPT=$(echo "$BLUE%n:$GREEN%/$_YELLOW>$FINISH ")
export EDITOR=vim
hash -d T="/home/xiaobai/tmp"
hash -d H="/home/xiaobai/lenovo/Pform/src/main/webapp/html"
hash -d K="/home/xiaobai/knowledgeBaseRepo"
hash -d D="/home/xiaobai/Downloads"
hash -d P="/home/xiaobai/lenovo/Pform"
export JAVA_HOME=/usr/env/jdk8
export JRE_HOME=${JAVA_HOME}/jre
export CLASSPATH=.:${JAVA_HOME}/lib:${JRE_HOME}/lib
export MAVEN_HOME=/usr/env/maven3
export ANDROID_HOME=/opt/android-sdk
export PATH=${JAVA_HOME}/bin:${MAVEN_HOME}/bin:$PATH:/usr/env/scala/bin:/home/xiaobai/.gem/ruby/2.3.0/bin:/usr/env/scala/bin:/home/xiaobai/pear/bin:/usr/env/jmeter/bin:${ANDROID_HOME}/tools

#透明处理
if [ -n "$WINDOWID" ]; then
    TRANSPARENCY_HEX=$(printf 0x%x $((0xffffffff * 95 / 100)))
    xprop -id "$WINDOWID" -f _NET_WM_WINDOW_OPACITY 32c -set _NET_WM_WINDOW_OPACITY "$TRANSPARENCY_HEX"
fi

alias dstat='dstat -cdlmnpsy'
alias rcs='ssh xiaoi@10.120.22.28 -i ~/.ssh/xiao-tmp.pem'
alias lenovovpn='sudo openconnect webvpn.cn.lenovo.com'


#设置man颜色
man() {
    env LESS_TERMCAP_mb=$'\E[01;31m' \
    LESS_TERMCAP_md=$'\E[01;38;5;74m' \
    LESS_TERMCAP_me=$'\E[0m' \
    LESS_TERMCAP_se=$'\E[0m' \
    LESS_TERMCAP_so=$'\E[38;5;246m' \
    LESS_TERMCAP_ue=$'\E[0m' \
    LESS_TERMCAP_us=$'\E[04;38;5;146m' \
    man "$@"
}
alias pq='pacman -Q'
alias c='clear '
alias prscn='sudo pacman -Rscn '
alias svim='sudo vim '
alias sshxx='ssh mathweb@202.197.237.29'
alias wsearch='curl -4 wttr.in/haidian'
alias psyu='sudo pacman -Syu'
alias pss='sudo pacman -Ss '
alias yss='yaourt -Ss '
alias pas='sudo pacman -S '
alias nettest='ping -c 3 baidu.com'
alias cd2='cd ../../'
alias cd3='cd ../../../'
alias cd4='cd ../../../../'
alias pqdt='sudo pacman -Qdt'
alias sshtools='ssh lijl@10.99.23.88'
